package gitx

const (
	latestCommitFormat = "%(refname:short)%00%(subject)%00%(committerdate:unix)"
	uniqueCommitFormat = "%h%x00%s%x00%ct"
	nullByte           = "\x00"
)

const (
	kAdd         = "add"
	kBranch      = "branch"
	kClone       = "clone"
	kCommit      = "commit"
	kCommitTree  = "commit-tree"
	kConfig      = "config"
	kDiff        = "diff"
	kFetch       = "fetch"
	kForEachRef  = "for-each-ref"
	kGetURL      = "get-url"
	kGit         = "git"
	kHead        = "HEAD"
	kHeads       = "heads"
	kList        = "list"
	kLog         = "log"
	kLsRemote    = "ls-remote"
	kMerge       = "merge"
	kMove        = "move"
	kOrigin      = "origin"
	kPop         = "pop" // lmao... kpop
	kPrune       = "prune"
	kPush        = "push"
	kRebase      = "rebase"
	kRebaseApply = "rebase-apply"
	kRebaseMerge = "rebase-merge"
	kRefs        = "refs"
	kRemote      = "remote"
	kRemotes     = "remotes"
	kRemove      = "remove"
	kRepair      = "repair"
	kReset       = "reset"
	kRevList     = "rev-list"
	kRevParse    = "rev-parse"
	kSetHead     = "set-head"
	kShowRef     = "show-ref"
	kStash       = "stash"
	kStatus      = "status"
	kSymbolicRef = "symbolic-ref"
	kUpdateRef   = "update-ref"
	kWorktree    = "worktree"
)

const (
	dashB      = "-b"
	dashC      = "-c"
	dashM      = "-m"
	dashUpperA = "-A"
	dashUpperD = "-D"
)

const (
	flagAbbrevRef        = "--abbrev-ref"
	flagAbort            = "--abort"
	flagAuto             = "--auto"
	flagBare             = "--bare"
	flagCached           = "--cached"
	flagContinue         = "--continue"
	flagCount            = "--count"
	flagDelete           = "--delete"
	flagForce            = "--force"
	flagForceWithLease   = "--force-with-lease"
	flagFormat           = "--format"
	flagGitCommonDir     = "--git-common-dir"
	flagGitDir           = "--git-dir"
	flagHard             = "--hard"
	flagIsBareRepository = "--is-bare-repository"
	flagLeftRight        = "--left-right"
	flagMaxCount         = "--max-count"
	flagOnto             = "--onto"
	flagPorcelain        = "--porcelain"
	flagQuiet            = "--quiet"
	flagSetUpstream      = "--set-upstream"
	flagShort            = "--short"
	flagShowTopLevel     = "--show-toplevel"
	flagSquash           = "--squash"
	flagStaged           = "--staged"
	flagUnset            = "--unset"
	flagVerify           = "--verify"
)
